### ISSUE TITLE
uptest: pre/post hooks for tests that require manual intervention

### ISSUE THREAD

**Issue by muvaf** [upbound/uptest#3]
### What problem are you facing?

Some resources require manual interventions that we can actually handle in a bash script, like uploading a zip to S3 for Lambda Function to run but currently.

### How could Official Providers help solve your problem?

We can add pre/post hook script paths to the examples for Uptest to execute.

**Comment by sergenyalcin** [comment]
Pre-Post hook support was added to uptest.
