### ISSUE TITLE
Report tested example manifest instead of the file list hash if the file list contains a single file

### ISSUE THREAD

**Issue by ulucinar** [upbound/uptest#63]
### What problem are you facing?

When multiple uptest runs are triggered on the same commit in a PR, it becomes difficult to associate the workflow status reports back to the example manifests on which they were run. Uptest supports multiple example manifests to be specified as the test target in a single run, so currently we are reporting a hash of the concatenated manifest paths because a long list would not be appropriate to name a workflow status item. 

### How could Uptest help solve your problem?

It would be helpful to name the reported workflow status with the tested example manifest path if the example list contains one path. We can preserve the current behavior if the list contains more than one element so that the status report names do not grow too long.

**Comment by sergenyalcin** [comment]
https://github.com/upbound/uptest/pull/64
